import { Outfit } from 'next/font/google';
import LoginImage from 'public/images/login-page/login-image.svg';

import 'app/globals.css';

const outfit = Outfit({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-outfit',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${outfit.variable} `}>
      <body>
        <main className="flex min-h-screen flex-col items-center">
          <div className="flex w-full grow">
            <div className="mx-14 flex flex-1 grow justify-center py-8">
              <div className="flex w-full max-w-[500px] flex-col">
                <p className="mr-auto font-medium">Shefu</p>
                {children}
              </div>
            </div>
            <div className="sticky top-0 flex h-screen flex-1 grow flex-col items-center justify-center rounded-lg bg-secondary-blue">
              <LoginImage />
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
